name: Bug Report 🐛
description: Report a problem you encountered with Kohl's Admin
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Have you searched for existing bugs? 🔍
      description: You can do this by searching https://github.com/kohls-admin/kohls-admin/issues?q=is:issue+label:bug and making sure the bug is not related.
      options:
        - label: I have searched the open and **closed** bugs.
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing the problem on?
      options:
        - PC
        - Mobile
        - Console
        - VR
      default: 0

  - type: input
    id: ver
    attributes:
      label: Kohl's Admin Version 🔢
      description: Include the version from the `;about` or `;version` commands.
      placeholder: ex. 8aebbd4
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: What Happened? 🤔
      description: Describe what went wrong in detail.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce 🪜
      description: Provide clear directions so someone else can see the issue on their machine too.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Evidence (logs, errors, images, videos) 📎
      description: |
        Attach anything that helps explain the problem.
        * **Logs:** Use the `;logs` command.
        * **Errors:** Press `F9` or type `/console` in chat.
        **Please ATTACH files, don't paste them directly.**
