name: Feature Request ✨
description: Suggest an improvement or new feature for Kohl's Admin
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Have you searched for similar requests? 🕵️‍♀️
      description: Please confirm you've checked if someone else already suggested this.
      options:
        - label: I've searched open and closed feature requests.
          required: true

  - type: textarea
    id: desc
    attributes:
      label: Describe the Feature in Detail 📝
      description: Explain what you'd like to see added or changed, and why it's valuable.
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Situation/Workaround 🔄
      description: How are you handling things now, or is there a less ideal way to achieve this?
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits 🚀
      description: How would this feature improve Kohl's Admin for you and others?
    validations:
      required: false
