name: CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: CI and Deployment
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: Roblox/setup-foreman@v1
        with:
          version: "*"
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-org: true
      - run: foreman --version
      - run: rojo --version

      - name: Deploy Testing Place
        run: rojo upload --api_key "$PLACE_PUBLISHING_KEY" --universe_id 6195299643 --asset_id 18274376677
        env:
          PLACE_PUBLISHING_KEY: ${{ secrets.PLACE_PUBLISHING_KEY }}
