name: CI

on:
  push:
    branches:
      - master
      - testing

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: "*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: rokit --version
      - run: rojo --version

      - name: Publish Test Place
        run: rojo upload --api_key "${{ secrets.PLACE_PUBLISHING_KEY }}" --universe_id ${{ secrets.TEST_UNIVERSE_ID }} --asset_id ${{ secrets.TEST_PLACE_ID }} test
