name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Publish changes to Roblox and bump version
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Modify VERSION.txt
        run: echo "$(git rev-parse --short HEAD)" > VERSION.txt

      - name: Bump version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump version
          file_pattern: VERSION.txt

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: "*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: foreman --version
      - run: rojo --version

      - name: Publish Test Place
        run: rojo upload --api_key "${{ secrets.PLACE_PUBLISHING_KEY }}" --universe_id ${{ secrets.TEST_UNIVERSE_ID }} --asset_id ${{ secrets.TEST_PLACE_ID }} test.project.json

      - name: Publish Test Loader
        run: rojo upload --asset_id ${{ secrets.TEST_LOADER_ID }} --cookie "${{ secrets.ROBLOSECURITY }}" .github/loader.project.json
